# Do not change version. This is the version of aws buildspec, not the version of your buldspec file.
version: 0.2
phases:
  pre_build:
    commands:
      - echo Installing NPM dependencies...
      - npm install
  build:
    commands:
      - npm run-script build
# Include only the files required for your application to run.
artifacts:
  files:
    - index.js
    - api/
    - config/
    - helpers/
    - middleware/
    - node_modules/**/*
